name: PHP CodeSniffer Style Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     - uses: MilesChou/composer-action@master
        with:
           args: install
           args: test
      env:
        CI: true
